# Generated by Django 2.1.4 on 2019-06-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='offersDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_img', models.ImageField(upload_to='pics')),
                ('offer_type', models.CharField(max_length=50)),
                ('offer_desc', models.CharField(max_length=100)),
            ],
        ),
    ]
