# Generated by Django 2.1.4 on 2019-06-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_offersdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.ImageField(upload_to='pics')),
                ('about_heading', models.CharField(max_length=100)),
                ('about_desc', models.CharField(max_length=100)),
                ('about_icon', models.ImageField(upload_to='pics')),
                ('why_banner', models.ImageField(upload_to='pics')),
                ('card_img', models.ImageField(upload_to='pics')),
                ('card_title', models.CharField(max_length=100)),
                ('card_desc', models.CharField(max_length=100)),
                ('team_img', models.ImageField(upload_to='pics')),
                ('team_name', models.CharField(max_length=20)),
                ('team_desc', models.CharField(max_length=100)),
            ],
        ),
    ]
